### PR TITLE
To work with v0.7 (renaming, replacing LinAlg, some Base -> LinearAlgebra)

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
I have not run the tests -- bcz running a branch is not my forte.

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
wait -- I found more stuff to tweak

**Comment by andreasnoack** [comment]
Thanks. I'm busy with other stuff for the time being but will review as soon as possible.

**Comment by andreasnoack** [comment]
Sorry for the wasted efforts here but I had to make some other changes as well and decided it was simpler to start over.

**Comment by JeffreySarnoff** [comment]
I understand and agree.

**Pull request closed without merging**
